# Generated by Django 6.0.1 on 2026-04-27 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bible_content', '0001_initial'),
        ('curriculum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(choices=[('cloze', 'Completar espacio (Cloze)'), ('type_in', 'Escribir respuesta'), ('scramble', 'Ordenar palabras'), ('selection', 'Selección múltiple'), ('true_false', 'Verdadero o Falso')], max_length=20)),
                ('question_data', models.JSONField(help_text='Datos de la pregunta (formato depende del tipo de ejercicio)')),
                ('answer_data', models.JSONField(help_text='Datos de la respuesta correcta')),
                ('difficulty', models.IntegerField(choices=[(1, 'Fácil'), (2, 'Medio'), (3, 'Difícil')], default=1)),
                ('order', models.IntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='curriculum.lesson')),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='bible_content.verse')),
            ],
            options={
                'verbose_name': 'Ejercicio',
                'verbose_name_plural': 'Ejercicios',
                'ordering': ['lesson', 'order'],
            },
        ),
        migrations.CreateModel(
            name='UserExerciseAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField()),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('time_spent_seconds', models.IntegerField(default=0, help_text='Time spent on this exercise in seconds')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exercises.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Intento de Ejercicio',
                'verbose_name_plural': 'Intentos de Ejercicios',
                'ordering': ['-answered_at'],
            },
        ),
    ]
