# Generated by Django 6.0.1 on 2026-04-27 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del libro (ej. Génesis)', max_length=100)),
                ('abbreviation', models.CharField(help_text='Abreviatura (ej. Gn)', max_length=10)),
                ('testament', models.CharField(choices=[('AT', 'Antiguo Testamento'), ('NT', 'Nuevo Testamento')], max_length=2)),
                ('order', models.IntegerField(help_text='Orden en la Biblia (1=Génesis)', unique=True)),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TheologicalTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('tema', 'Tema'), ('festividad', 'Festividad'), ('profecia', 'Profecía'), ('doctrina', 'Doctrina'), ('personaje', 'Personaje')], default='tema', max_length=20)),
            ],
            options={
                'verbose_name': 'Etiqueta Teológica',
                'verbose_name_plural': 'Etiquetas Teológicas',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='Número de capítulo')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='bible_content.book')),
            ],
            options={
                'verbose_name': 'Capítulo',
                'verbose_name_plural': 'Capítulos',
                'ordering': ['book', 'number'],
                'unique_together': {('book', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='Número de versículo')),
                ('text', models.TextField(help_text='Texto del versículo')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='bible_content.chapter')),
            ],
            options={
                'verbose_name': 'Versículo',
                'verbose_name_plural': 'Versículos',
                'ordering': ['chapter', 'number'],
                'unique_together': {('chapter', 'number')},
            },
        ),
        migrations.CreateModel(
            name='VerseTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='bible_content.theologicaltag')),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='bible_content.verse')),
            ],
            options={
                'verbose_name': 'Etiqueta de Versículo',
                'verbose_name_plural': 'Etiquetas de Versículos',
                'unique_together': {('verse', 'tag')},
            },
        ),
    ]
