# Generated by Django 6.0.1 on 2026-04-27 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hearts', models.IntegerField(default=5, help_text='Vidas disponibles (máx 5)')),
                ('gems', models.IntegerField(default=0, help_text='Gemas acumuladas')),
                ('streak_days', models.IntegerField(default=0, help_text='Días consecutivos de práctica')),
                ('total_xp', models.IntegerField(default=0, help_text='Experiencia total acumulada')),
                ('last_practice_date', models.DateField(blank=True, null=True)),
                ('last_heart_regen', models.DateTimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='America/Bogota', max_length=50)),
                ('theological_preferences', models.JSONField(blank=True, default=dict, help_text='Preferencias teológicas del usuario (ej. excluir festividades)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
    ]
